# Generated by Django 3.2.2 on 2021-05-09 08:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9912c7d2-2c8a-4ea1-bc76-950af2729e36'), editable=False, primary_key=True, serialize=False)),
                ('use', models.CharField(choices=[('H', 'home'), ('W', 'work'), ('T', 'temporary'), ('O', 'old'), ('B', 'billing')], max_length=1)),
                ('type', models.CharField(choices=[('PO', 'postal'), ('PH', 'physical'), ('BO', 'both')], max_length=2)),
                ('text', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=5)),
                ('district', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=5)),
                ('postalCode', models.CharField(max_length=5, verbose_name='post code')),
                ('country', models.CharField(default='MY', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('84155122-12fc-458b-9c64-a80bcc4118e1'), editable=False, primary_key=True, serialize=False)),
                ('system', models.CharField(choices=[('phone', 'phone'), ('fax', 'fax'), ('email', 'E-mail'), ('url', 'url'), ('sms', 'sms')], max_length=5)),
                ('value', models.CharField(max_length=255)),
                ('use', models.CharField(choices=[('H', 'home'), ('W', 'work'), ('T', 'temporary'), ('O', 'old'), ('B', 'billing')], max_length=1)),
                ('type', models.CharField(choices=[('PO', 'postal'), ('PH', 'physical'), ('BO', 'both')], max_length=2)),
                ('rank', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ManagingOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f5b3e99d-1ccd-4555-947c-fd4b794f7ad4'), editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=1)),
                ('type', models.CharField(choices=[('prov', 'healthcare provider'), ('dept', 'hospital department'), ('team', 'organizational team'), ('govt', 'government'), ('ins', 'insurance company'), ('edu', 'educational institution'), ('reli', 'religious institution'), ('crs', 'clinical research sponsor'), ('cg', 'community group'), ('bus', 'non-healthcare business or corporation'), ('other', 'other')], max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.address')),
                ('telecom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.contactpoint')),
            ],
        ),
        migrations.AlterField(
            model_name='humanname',
            name='id',
            field=models.UUIDField(default=uuid.UUID('49e42f76-07a2-4566-a247-b749a4f7f8b4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8e08a1e0-9b54-45ed-93a1-a1c1c04e0ea7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ManagingOrganizationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('12730174-3dbf-4c21-b900-be40bc2dc7c0'), editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=1)),
                ('purpose', models.CharField(choices=[('bill', 'billing'), ('admin', 'administrative enquiries'), ('hr', 'human resources'), ('payor', 'insurance claims and payments'), ('patif', 'patient information'), ('press', 'press enquiries')], max_length=5)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.person')),
                ('managingorganization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.managingorganization')),
            ],
        ),
        migrations.AddField(
            model_name='contactpoint',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.person'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3604428c-d50e-4dd4-8c34-5ba49b332c8e'), editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=3)),
                ('preferred', models.BooleanField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.person')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.person'),
        ),
    ]
