# Generated by Django 3.2.2 on 2021-05-09 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210509_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c6f50766-842b-49eb-ade8-99956fdf5930'), editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1dc6179a-e8a1-4124-baf0-9dbf83d9896e'), editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=12)),
                ('text', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('cd697ae0-e34e-4017-b70b-8572cb2659d2'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('76f0baa7-6541-4f72-80fe-868a2c169f67'), editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=12)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('91fbcc88-2561-4b8c-9848-43ba498556fe'), editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=12)),
                ('text', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9aa877aa-16a4-42af-8057-904576f978bc'), editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=12)),
                ('text', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='managingorganizationcontact',
            old_name='managingorganization',
            new_name='managingOrganization',
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3daaf50f-c72d-484d-9f16-302f17fd3bde'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communication',
            name='id',
            field=models.UUIDField(default=uuid.UUID('82204cc9-f6b8-4914-9e9a-7dc2e7e34afd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2b0562b-2ba2-4b47-9b08-ef9327586e7b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='humanname',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10c8205e-4396-420b-b167-175fce6e4c62'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='managingorganization',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7ab92ea7-595e-4219-ab72-97d58c43a5d7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='managingorganizationcontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('537e2de5-a4e0-4f4f-a465-983b7dedb71e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9b5e802-42c2-402e-ba05-361aaf26af78'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PractitionerRole',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1e351ba7-c71c-4358-98a2-041993a56ffa'), editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.location')),
                ('managingOrganization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.managingorganization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.role')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('51cf0963-c7f0-4cc8-bb66-b81bd902a44f'), editable=False, primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.person')),
                ('practitionerRole', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.practitionerrole')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('730d7747-8c1a-4789-9326-3ddc8839719a'), editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=1)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.contact')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='managingOrganization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.managingorganization'),
        ),
        migrations.AddField(
            model_name='patient',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.person'),
        ),
        migrations.AddField(
            model_name='contact',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.patient'),
        ),
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.person'),
        ),
    ]
