# Generated by Django 3.2.2 on 2021-05-09 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210509_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a1363cd0-9aa4-42df-99db-6dd6c0d23dc3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communication',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d7c04b43-ea52-4455-83a2-e6bd4d9932c3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0de9a762-5028-4a44-8343-13b882094d00'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contactpoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('900b4164-76b3-4618-95ce-28cfb2c9ec87'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosticorder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('168721a3-8879-41a0-a591-4890a6818a5c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='humanname',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ec2cab3c-574d-42ff-a9a0-7251ae798ef2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1137b0bf-661f-4603-b14b-401da2f9dbeb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='managingorganization',
            name='id',
            field=models.UUIDField(default=uuid.UUID('385b48fe-06a6-471c-9487-19703b644813'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='managingorganizationcontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('55c7e046-a81a-4054-bff7-b3d47c503eb7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2d504af-c405-41f2-8ed5-d55f8b688795'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='id',
            field=models.UUIDField(default=uuid.UUID('67a3f666-1b00-40e2-9448-5766c3186101'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='deceasedDate',
            field=models.DateField(null=True, verbose_name='deceased date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.UUID('132fb2e6-9ac3-41aa-bce4-6d5da5ccb5db'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85f46def-c6bc-4c0a-ad3f-62a81157a6e5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='practitionerrole',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9ff5c7d-64cf-497b-983c-ea85fd7591a6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('843003a4-38ef-4f27-887c-889576b7c402'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73a6d335-472c-4bc2-ab6f-cfe6d98361dc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='id',
            field=models.UUIDField(default=uuid.UUID('733e43e4-bb75-4247-a183-970f0a0f2fca'), editable=False, primary_key=True, serialize=False),
        ),
    ]
